"""
CI/CD asset generator — Phase 9.

Spec (phases.md, PHASE 9, "CI/CD Integration"):
    "Provide a GitHub Actions workflow and pre-commit hook that:
       - Runs Phase 1 + Phase 2 on every PR touching .sol files
       - Posts a summary comment to the PR with any new invariant violations
       - Blocks merge if critical findings are present (configurable)
       - Stores results in Phase 8 knowledge graph automatically"

This module ships those assets as templates and writes them on demand. No
hidden side effects at import time; callers explicitly invoke
``write_github_actions(...)`` / ``write_pre_commit(...)``.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


_GITHUB_ACTIONS_TEMPLATE = """\
# Generated by ZeroPath Phase 9 — CI/CD integration.
# Runs Phase 1 (protocol graph) + Phase 2 (invariants) on every PR that
# touches Solidity files, comments findings, and (optionally) blocks merge.

name: ZeroPath Security Audit

on:
  pull_request:
    paths:
      - "**/*.sol"
      - "**/*.vy"

permissions:
  contents: read
  pull-requests: write

jobs:
  audit:
    runs-on: ubuntu-latest
    env:
      ZEROPATH_BLOCK_ON_CRITICAL: "{block_on_critical}"
      ZEROPATH_KG_URL: ${{{{ secrets.ZEROPATH_KG_URL }}}}      # optional Neo4j
      ZEROPATH_KG_USER: ${{{{ secrets.ZEROPATH_KG_USER }}}}
      ZEROPATH_KG_PASSWORD: ${{{{ secrets.ZEROPATH_KG_PASSWORD }}}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "{python_version}"

      - name: Install ZeroPath
        run: |
          python -m pip install --upgrade pip
          python -m pip install zeropath

      - name: Run Phase 1 + 2
        run: |
          zeropath analyze ./{contracts_dir} \\
            --output-json zeropath-report.json \\
            --output-markdown zeropath-report.md

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: zeropath-report
          path: |
            zeropath-report.md
            zeropath-report.json

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: zeropath
          path: zeropath-report.md

      - name: Gate merge on critical findings
        if: env.ZEROPATH_BLOCK_ON_CRITICAL == 'true'
        run: |
          python - <<'PY'
          import json, sys
          report = json.load(open("zeropath-report.json"))
          critical = report.get("summary", {{}}).get("by_severity", {{}}).get("critical", 0)
          if critical > 0:
              print(f"::error::ZeroPath found {{critical}} critical finding(s) — blocking merge.")
              sys.exit(1)
          PY
"""


_PRE_COMMIT_TEMPLATE = """\
# Generated by ZeroPath Phase 9 — local pre-commit hook.
# Runs a lightweight invariant scan over staged Solidity files. Designed to
# fail fast on critical findings before the commit lands.

- repo: local
  hooks:
    - id: zeropath-quick-scan
      name: ZeroPath quick invariant scan
      entry: zeropath scan --staged --fail-on critical
      language: system
      files: '\\.(sol|vy)$'
      pass_filenames: true
      stages: [commit]
"""


_README_TEMPLATE = """\
# ZeroPath CI/CD Integration

This directory holds the assets generated by `zeropath.reporting.CICDAssetGenerator`.

## Files

* `.github/workflows/zeropath.yml` — GitHub Actions workflow.
  Runs Phase 1 + 2 on every PR touching `.sol` / `.vy` files, posts a
  sticky PR comment with the Markdown report, and (when
  `ZEROPATH_BLOCK_ON_CRITICAL=true`) fails the workflow on any CRITICAL
  finding.

* `.pre-commit-config.yaml` — local pre-commit hook.
  Runs `zeropath scan --staged --fail-on critical` before each commit
  for fast feedback.

## Optional secrets

To enable Phase 8 knowledge-graph persistence in CI, add these to your
GitHub repository secrets:

| Secret name | Value |
|---|---|
| `ZEROPATH_KG_URL` | Neo4j bolt URL (e.g. `bolt://my-neo4j:7687`) |
| `ZEROPATH_KG_USER` | Neo4j username |
| `ZEROPATH_KG_PASSWORD` | Neo4j password |

Without them, the action still runs and reports — it just won't persist
findings into the long-term knowledge graph.
"""


class CICDAssetGenerator:
    """
    Write the GitHub Actions workflow + pre-commit hook templates into a
    target directory.

    Parameters
    ----------
    contracts_dir : str
        Path the CI workflow should pass to `zeropath analyze`. Defaults
        to ``contracts``.
    python_version : str
        Python version used in the GitHub Actions runner.
    block_on_critical : bool
        Whether the rendered workflow defaults to blocking merge on
        CRITICAL findings. The flag is also overridable at runtime via the
        ``ZEROPATH_BLOCK_ON_CRITICAL`` env var.
    """

    def __init__(
        self,
        *,
        contracts_dir: str = "contracts",
        python_version: str = "3.11",
        block_on_critical: bool = True,
    ) -> None:
        self.contracts_dir = contracts_dir
        self.python_version = python_version
        self.block_on_critical = block_on_critical

    # ------------------------------------------------------------------
    # Template renderers
    # ------------------------------------------------------------------

    def render_github_actions(self) -> str:
        return _GITHUB_ACTIONS_TEMPLATE.format(
            contracts_dir=self.contracts_dir,
            python_version=self.python_version,
            block_on_critical=str(self.block_on_critical).lower(),
        )

    def render_pre_commit(self) -> str:
        return _PRE_COMMIT_TEMPLATE

    def render_readme(self) -> str:
        return _README_TEMPLATE

    # ------------------------------------------------------------------
    # File writers
    # ------------------------------------------------------------------

    def write_github_actions(
        self, root: str | Path, *, filename: str = "zeropath.yml",
    ) -> Path:
        target = Path(root) / ".github" / "workflows" / filename
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(self.render_github_actions(), encoding="utf-8")
        return target

    def write_pre_commit(
        self, root: str | Path, *, filename: str = ".pre-commit-config.yaml",
    ) -> Path:
        target = Path(root) / filename
        # Pre-commit configs are commonly merged with existing hooks. If
        # the file exists, append the ZeroPath block instead of overwriting.
        block = self.render_pre_commit()
        if target.exists():
            existing = target.read_text(encoding="utf-8")
            if "id: zeropath-quick-scan" in existing:
                return target
            new = existing.rstrip() + "\n\nrepos:\n" + block + "\n"
            target.write_text(new, encoding="utf-8")
        else:
            target.write_text("repos:\n" + block, encoding="utf-8")
        return target

    def write_all(self, root: str | Path) -> dict[str, Path]:
        root = Path(root)
        wf = self.write_github_actions(root)
        pc = self.write_pre_commit(root)
        readme = root / "ZEROPATH_CICD.md"
        readme.write_text(self.render_readme(), encoding="utf-8")
        return {"github_actions": wf, "pre_commit": pc, "readme": readme}
