"""`zeropath prove` command surface."""

from pathlib import Path

import click
from rich.console import Console

if not hasattr(click, "Exit"):
    click.Exit = click.exceptions.Exit

console = Console()


@click.command("prove")
@click.argument("candidate_id")
@click.option("--repo", type=click.Path(file_okay=False, path_type=Path), default=Path("."), show_default=True)
@click.option("--backend", type=click.Choice(["foundry"]), default="foundry", show_default=True)
@click.option("--write-test-dir", is_flag=True, help="Also write a Foundry test under test/zeropath if safe.")
@click.option("--force", is_flag=True, help="Allow overwriting generated Foundry test file.")
@click.option("--run/--no-run", default=True, show_default=True, help="Run backend proof if available.")
def prove(candidate_id: str, repo: Path, backend: str, write_test_dir: bool, force: bool, run: bool) -> None:
    """Generate a candidate proof skeleton and optionally run a backend."""
    from zeropath.adapters.evm import EVMAdapter
    from zeropath.adapters.evm.forge import run_forge_test
    from zeropath.adapters.evm.foundry import runnable_candidate_test_path, write_candidate_test
    from zeropath.core.state_plan import get_or_build_candidate_state_plan
    from zeropath.core.storage import Storage

    storage = Storage(repo)
    candidate = storage.load_candidate(candidate_id)
    if candidate is None:
        console.print(f"[red]Candidate not found:[/red] {candidate_id}")
        raise click.Exit(1)
    adapter = EVMAdapter(repo)
    state_plan = get_or_build_candidate_state_plan(storage, candidate_id)
    poc = adapter.generate_poc(candidate, state_plan=state_plan)
    if not poc:
        console.print("[yellow]PoC could not be generated by the adapter.[/yellow]")
        raise click.Exit(1)
    artifact = storage.append_artifact(Path("pocs") / f"{candidate.id.replace('-', '_')}.t.sol", poc, overwrite=True)
    candidate.evidence.poc_path = str(artifact)
    candidate.status = "poc_generated"
    if state_plan.artifact_path:
        candidate.evidence.notes.append(f"PoC generated from state plan {state_plan.artifact_path}")
    else:
        candidate.evidence.notes.append("PoC generated from transient state plan; run `zeropath candidates plan` to persist it.")
    if write_test_dir:
        try:
            test_path = write_candidate_test(repo, candidate, state_plan=state_plan, force=force)
            candidate.evidence.notes.append(f"Foundry test written to {test_path}")
        except FileExistsError as exc:
            console.print(f"[red]{exc}[/red]")
            raise click.Exit(1)
    if run and backend == "foundry":
        result = run_forge_test(repo, runnable_candidate_test_path(repo, candidate))
        candidate.evidence.forge_result = result.get("status")
        candidate.evidence.notes.append(result.get("message") or f"forge test status: {result.get('status')}")
        if result.get("status") == "passed":
            candidate.status = "poc_passed"
    storage.save_candidate(candidate)
    console.print(f"[green]PoC skeleton:[/green] {artifact}")
    console.print(f"Forge result: {candidate.evidence.forge_result or 'not run'}")


__all__ = ["prove"]
