"""`zeropath prove` command surface."""

from pathlib import Path

import click
from rich.console import Console

if not hasattr(click, "Exit"):
    click.Exit = click.exceptions.Exit

console = Console()


@click.command("prove")
@click.argument("candidate_id")
@click.option("--repo", type=click.Path(file_okay=False, path_type=Path), default=Path("."), show_default=True)
@click.option("--backend", type=click.Choice(["foundry"]), default="foundry", show_default=True)
@click.option("--write-test-dir", is_flag=True, help="Also write a Foundry test under test/zeropath if safe.")
@click.option("--force", is_flag=True, help="Allow overwriting generated Foundry test file.")
@click.option("--run/--no-run", default=True, show_default=True, help="Run backend proof if available.")
def prove(candidate_id: str, repo: Path, backend: str, write_test_dir: bool, force: bool, run: bool) -> None:
    """Generate a candidate proof skeleton and optionally run a backend."""
    from zeropath.adapters.evm import EVMAdapter
    from zeropath.adapters.evm.forge import run_forge_test, save_forge_trace
    from zeropath.adapters.evm.foundry import (
        candidate_test_path,
        runnable_candidate_test_path,
        write_candidate_test,
        write_runnable_poc,
    )
    from zeropath.adapters.evm.inflation_poc import (
        apply_inflation_proof_evidence,
        parse_measured_events,
        render_inflation_poc,
    )
    from zeropath.core.state_plan import get_or_build_candidate_state_plan
    from zeropath.core.storage import Storage

    storage = Storage(repo)
    candidate = storage.load_candidate(candidate_id)
    if candidate is None:
        console.print(f"[red]Candidate not found:[/red] {candidate_id}")
        raise click.Exit(1)
    adapter = EVMAdapter(repo)
    _ensure_adapter_index(adapter, storage)
    state_plan = get_or_build_candidate_state_plan(storage, candidate_id)
    inflation_targets = adapter.detect_inflation_targets(candidate)
    poc = adapter.generate_poc(candidate, state_plan=state_plan)
    if not poc:
        console.print("[yellow]PoC could not be generated by the adapter.[/yellow]")
        raise click.Exit(1)
    artifact = storage.append_artifact(Path("pocs") / f"{candidate.id.replace('-', '_')}.t.sol", poc, overwrite=True)
    candidate.evidence.poc_path = str(artifact)
    candidate.status = "poc_generated"
    runnable_path: Path | None = None
    if inflation_targets is not None:
        candidate.evidence.notes.append(
            f"Executable inflation PoC generated against {inflation_targets.vault_contract} "
            f"+ {inflation_targets.asset_contract} from {inflation_targets.source_file}."
        )
        # Forge only auto-discovers tests under the configured test/ directory,
        # so we also write the runnable copy there (with the import path
        # adjusted for the new location) and run forge against it.
        runnable_source = render_inflation_poc(
            candidate, inflation_targets, poc_location="test/zeropath"
        )
        runnable_path = write_runnable_poc(repo, candidate, runnable_source)
        candidate.evidence.notes.append(
            f"Runnable Foundry test written to {runnable_path}"
        )
    elif state_plan.artifact_path:
        candidate.evidence.notes.append(f"PoC generated from state plan {state_plan.artifact_path}")
    else:
        candidate.evidence.notes.append("PoC generated from transient state plan; run `zeropath candidates plan` to persist it.")
    if write_test_dir and inflation_targets is None:
        try:
            test_path = write_candidate_test(repo, candidate, state_plan=state_plan, force=force)
            candidate.evidence.notes.append(f"Foundry test written to {test_path}")
        except FileExistsError as exc:
            console.print(f"[red]{exc}[/red]")
            raise click.Exit(1)
    if run and backend == "foundry":
        verbosity = 4 if inflation_targets is not None else 0
        match_path = runnable_path or runnable_candidate_test_path(repo, candidate)
        result = run_forge_test(
            repo,
            match_path,
            verbosity=verbosity,
        )
        candidate.evidence.forge_result = result.get("status")
        candidate.evidence.trace_path = str(save_forge_trace(storage, candidate, result))
        candidate.evidence.notes.append(result.get("message") or f"forge test status: {result.get('status')}")
        if inflation_targets is not None:
            measured = parse_measured_events(result.get("stdout") or "")
            apply_inflation_proof_evidence(candidate, result, measured)
        if result.get("status") == "passed":
            candidate.status = "poc_passed"
    storage.save_candidate(candidate)
    console.print(f"[green]PoC artifact:[/green] {artifact}")
    console.print(f"Forge result: {candidate.evidence.forge_result or 'not run'}")
    if candidate.impact.measured and candidate.impact.amount:
        console.print(f"Impact: {candidate.impact.amount}")


def _ensure_adapter_index(adapter, storage) -> None:
    """Load the persisted EVM index into the adapter (or ingest fresh)."""

    index = storage.load_record("ingest", "evm_index")
    if index:
        # Bypass full ingest_project: just attach the persisted index.
        adapter._index = index  # type: ignore[attr-defined]
        return
    config = storage.load_project_config()
    adapter.ingest_project(config)


__all__ = ["prove"]
