"""
Data models for Phase 3: Adversarial Attack Hypothesis Swarm.

Each AttackHypothesis is a concrete, testable exploit path inferred from a
Phase 2 Invariant.  The SwarmReport is the root output of one full Phase 3 run.

Downstream phases:
  Phase 4  — Transaction Sequence Generator (converts hypotheses → tx chains)
  Phase 5  — EVM Simulation Engine (Foundry-based execution)
  Phase 6  — Exploit Validation Engine (kills false positives)
"""

from enum import Enum
from typing import Any, Optional
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------


class AttackClass(str, Enum):
    """High-level class of the attack vector."""

    ORACLE_MANIPULATION = "oracle_manipulation"
    """Manipulate a price feed within one block to distort protocol accounting."""

    REENTRANCY = "reentrancy"
    """Re-enter a function during an external call before state is finalised."""

    ACCESS_CONTROL = "access_control"
    """Reach a privileged function without the required role or ownership."""

    FLASH_LOAN = "flash_loan"
    """Use borrowed capital atomically to distort state and extract value."""

    COMPOSABILITY = "composability"
    """Weaponise a third-party protocol's state against the target."""

    GOVERNANCE = "governance"
    """Capture or bypass governance to execute a malicious proposal."""

    INTEGER_MATH = "integer_math"
    """Exploit overflow, underflow, rounding, or precision loss."""

    PRICE_MANIPULATION = "price_manipulation"
    """Manipulate pool reserves or AMM state to change asset prices."""

    UNKNOWN = "unknown"


class HypothesisStatus(str, Enum):
    """Lifecycle state of a hypothesis."""

    PROPOSED = "proposed"
    """Generated by a single agent, not yet debated."""

    ENDORSED = "endorsed"
    """Confirmed by at least one other agent in the debate round."""

    CHALLENGED = "challenged"
    """Disputed by at least one other agent; still a candidate."""

    REJECTED = "rejected"
    """Consensus: the hypothesis is not viable (wrong preconditions, etc.)."""

    CONSENSUS = "consensus"
    """Majority of relevant agents agreed this is valid."""


class ConditionType(str, Enum):
    """Category of a precondition for an attack."""

    FLASH_LOAN_AVAILABLE = "flash_loan_available"
    ORACLE_READ_SINGLE_BLOCK = "oracle_read_single_block"
    EXTERNAL_CALL_BEFORE_UPDATE = "external_call_before_update"
    UNGUARDED_FUNCTION = "unguarded_function"
    GOVERNANCE_TOKEN_AVAILABLE = "governance_token_available"
    NO_TIMELOCK = "no_timelock"
    FEE_ON_TRANSFER_TOKEN = "fee_on_transfer_token"
    UPGRADEABLE_PROXY = "upgradeable_proxy"
    UNINITIALIZED_IMPL = "uninitialized_impl"
    CROSS_PROTOCOL_DEPENDENCY = "cross_protocol_dependency"
    OPEN_CALL = "open_call"
    INTEGER_TRUNCATION = "integer_truncation"
    CUSTOM = "custom"


# ---------------------------------------------------------------------------
# Sub-models
# ---------------------------------------------------------------------------


class AttackStep(BaseModel):
    """A single step in an exploit transaction sequence."""

    model_config = ConfigDict(populate_by_name=True)

    step: int = Field(description="1-indexed step number")
    action: str = Field(description="What the attacker does (imperative sentence)")
    target_contract: Optional[str] = Field(None, description="Contract being called")
    target_function: Optional[str] = Field(None, description="Function being called")
    purpose: str = Field(description="Why this step is necessary")
    estimated_gas: Optional[int] = Field(None)


class Precondition(BaseModel):
    """A condition that must hold for the attack to be viable."""

    model_config = ConfigDict(populate_by_name=True)

    condition_type: ConditionType = ConditionType.CUSTOM
    description: str
    is_met_by_protocol: Optional[bool] = Field(
        None, description="True if the protocol graph confirms this condition holds"
    )
    evidence: str = ""


class ProfitMechanism(BaseModel):
    """How the attacker extracts value."""

    model_config = ConfigDict(populate_by_name=True)

    description: str
    asset: str = Field(description="Asset extracted (ETH, ERC20 name, NFT, etc.)")
    estimated_max_usd: Optional[int] = Field(
        None, description="Upper bound loss estimate in USD (None = unknown)"
    )
    depends_on_protocol_tvl: bool = Field(
        True, description="Loss scales with protocol TVL"
    )


class DebateNote(BaseModel):
    """A critique or endorsement submitted by one agent about another's hypothesis."""

    model_config = ConfigDict(populate_by_name=True)

    from_agent: str = Field(description="Agent name submitting this note")
    verdict: str = Field(description="endorse | challenge | reject")
    reasoning: str = Field(description="Why the agent agrees or disagrees")
    confidence_delta: float = Field(
        0.0,
        ge=-0.4,
        le=0.4,
        description="How much this note shifts the hypothesis confidence",
    )


# ---------------------------------------------------------------------------
# Core hypothesis model
# ---------------------------------------------------------------------------


class AttackHypothesis(BaseModel):
    """
    A single concrete, testable exploit path inferred by one adversarial agent.

    Produced by the swarm and consumed by:
      Phase 4 (transaction sequence generator)
      Phase 6 (exploit validation engine)
    """

    model_config = ConfigDict(populate_by_name=True)

    id: str = Field(default_factory=lambda: str(uuid4()))

    # Source invariant
    invariant_id: str = Field(description="ID of the Phase 2 Invariant being exploited")
    invariant_description: str = Field(description="Human-readable invariant text")

    # Classification
    attack_class: AttackClass = AttackClass.UNKNOWN
    title: str = Field(description="Short (< 80 chars) name for the exploit")

    # Generating agent
    proposed_by: str = Field(description="Agent name that generated this hypothesis")

    # Concrete exploit description
    attack_narrative: str = Field(
        description="Paragraph describing the exploit from start to finish"
    )
    exploit_steps: list[AttackStep] = Field(
        default_factory=list,
        description="Ordered sequence of concrete transaction steps",
    )
    preconditions: list[Precondition] = Field(
        default_factory=list,
        description="Conditions that must hold for the exploit to work",
    )
    profit_mechanism: Optional[ProfitMechanism] = None

    # Protocol graph references
    contracts_involved: list[str] = Field(default_factory=list)
    functions_involved: list[str] = Field(default_factory=list)
    state_vars_involved: list[str] = Field(default_factory=list)

    # Historical grounding
    historical_precedent_protocols: list[str] = Field(
        default_factory=list,
        description="Real-world protocols exploited via the same vector",
    )
    historical_loss_usd: Optional[int] = Field(
        None, description="Highest known loss for this attack class"
    )

    # Debate / consensus
    status: HypothesisStatus = HypothesisStatus.PROPOSED
    debate_notes: list[DebateNote] = Field(default_factory=list)
    endorsing_agents: list[str] = Field(default_factory=list)
    dissenting_agents: list[str] = Field(default_factory=list)
    agent_consensus_score: float = Field(
        0.0, ge=0.0, le=1.0, description="Fraction of relevant agents that endorsed"
    )

    # Quality scores
    confidence: float = Field(0.5, ge=0.0, le=1.0)
    specificity_score: float = Field(
        0.5,
        ge=0.0,
        le=1.0,
        description="How concrete the hypothesis is (1.0 = fully specified tx sequence)",
    )

    # Suggested verification
    poc_sketch: str = Field(
        "",
        description="Minimal Foundry/Hardhat test sketch for rapid PoC development",
    )
    suggested_fix: str = Field("", description="Recommended remediation")


# ---------------------------------------------------------------------------
# Debate round
# ---------------------------------------------------------------------------


class DebateRound(BaseModel):
    """
    One round of inter-agent debate.  All agents review all peer hypotheses
    and submit DebateNotes, then final confidence is recomputed.
    """

    model_config = ConfigDict(populate_by_name=True)

    round_number: int = 1
    notes: list[DebateNote] = Field(default_factory=list)
    hypotheses_updated: int = 0
    hypotheses_rejected: int = 0


# ---------------------------------------------------------------------------
# Swarm report (root output of Phase 3)
# ---------------------------------------------------------------------------


class SwarmReport(BaseModel):
    """
    Complete output of one adversarial swarm run.

    Input:  Phase 2 InvariantReport
    Output: Ranked, debated list of concrete AttackHypotheses
    """

    model_config = ConfigDict(populate_by_name=True)

    id: str = Field(default_factory=lambda: str(uuid4()))
    protocol_name: str = "unknown"

    # Link back to Phase 2
    invariant_report_id: str = ""

    # The core findings — sorted by confidence DESC
    hypotheses: list[AttackHypothesis] = Field(default_factory=list)

    # Debate metadata
    debate_rounds: list[DebateRound] = Field(default_factory=list)

    # Per-agent participation summary
    agent_stats: dict[str, Any] = Field(default_factory=dict)

    # Run metadata
    analysis_metadata: dict[str, Any] = Field(default_factory=dict)

    # Convenience filters
    @property
    def critical_hypotheses(self) -> list[AttackHypothesis]:
        """Hypotheses with confidence >= 0.75 in consensus or endorsed state."""
        return [
            h for h in self.hypotheses
            if h.confidence >= 0.75
            and h.status in (HypothesisStatus.CONSENSUS, HypothesisStatus.ENDORSED)
        ]

    @property
    def by_attack_class(self) -> dict[AttackClass, list[AttackHypothesis]]:
        result: dict[AttackClass, list[AttackHypothesis]] = {}
        for h in self.hypotheses:
            result.setdefault(h.attack_class, []).append(h)
        return result

    @property
    def rejected_count(self) -> int:
        return sum(1 for h in self.hypotheses if h.status == HypothesisStatus.REJECTED)
